package entiteti;
// Generated Aug 9, 2018 5:02:59 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="movies"
)

// konstruktori, geteri i seteri za korisnika //

public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String pravaKorisnika;
     private String password;

    public User() {
        
    }

    
    
    /*public User(String name, String password) {
       this.name = name;
       this.password = password;
    }*/
    
    
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    
    
    @Column(name="prava_korisnika", length=45)
    public String getPravaKorisnika() {
        return this.pravaKorisnika;
    }
    
    public void setPravaKorisnika(String pravaKorisnika) {
        this.pravaKorisnika = pravaKorisnika;
    }




}


